//Local Development Values
const devtoolsPort = 8585;
const oadaDomain = 'https://localhost';
const websiteDomain = 'http://localhost:'+parseInt(window.location.port, 10);
const metadata = `
eyJqa3UiOiJodHRwczovL2lkZW50aXR5Lm9hZGEtZGV2LmNvbS9jZXJ0cyIsImtpZCI6ImtqY1NjamMzMmR3SlhYTEpEczNyMTI0c2ExIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJyZWRpcmVjdF91cmlzIjpbImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMC9vYXV0aDIvcmVkaXJlY3QuaHRtbCJdLCJ0b2tlbl9lbmRwb2ludF9hdXRoX21ldGhvZCI6InVybjppZXRmOnBhcmFtczpvYXV0aDpjbGllbnQtYXNzZXJ0aW9uLXR5cGU6and0LWJlYXJlciIsImdyYW50X3R5cGVzIjpbImltcGxpY2l0Il0sInJlc3BvbnNlX3R5cGVzIjpbInRva2VuIiwiaWRfdG9rZW4iLCJpZF90b2tlbiB0b2tlbiJdLCJjbGllbnRfbmFtZSI6IkFiY0F1ZGl0cyIsImNsaWVudF91cmkiOiJodHRwczovL2ZwYWQuaW8vIiwiY29udGFjdHMiOlsiU2FtIE5vZWwgPHNhbm9lbEBwdXJkdWUuZWR1PiJdLCJzb2Z0d2FyZV9pZCI6IjU5YmE3M2UyLWE4ZDgtNDRiNS1hODExLTdhMmNiYzk1OWUwOSIsInJlZ2lzdHJhdGlvbl9wcm92aWRlciI6Imh0dHBzOi8vaWRlbnRpdHkub2FkYS1kZXYuY29tIiwiaWF0IjoxNTA3ODI4NDY0fQ.xNWfc9zO-Hn1U-PXHRHY8ZNIQk6rDXEmvlEM_D-9C_iwbzNRWy_elUkFw5NCwQbhXkf-kdhFMoLQRQy_0d3V8BxE0cGnCJSYFiB7ULLDqYvLzTDvkeaJH1HaUGxfUyoVdsl4fUyoywlSfL4hJtK_2VcfrgvqWtfUHirq1M8pMyc
`.trim()

export default {
  oadaDomain,
  devtoolsPort,
  websiteDomain,
  metadata
}
