//Local Development Values
const devtoolsPort = 8585;
const oadaDomain = 'https://localhost';
const websiteDomain = 'http://localhost:'+parseInt(window.location.port, 10);
const metadata = `
eyJqa3UiOiJodHRwczovL2lkZW50aXR5Lm9hZGEtZGV2LmNvbS9jZXJ0cyIsImtpZCI6ImtqY1NjamMzMmR3SlhYTEpEczNyMTI0c2ExIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJyZWRpcmVjdF91cmlzIjpbImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMC9vYXV0aDIvcmVkaXJlY3QuaHRtbCJdLCJ0b2tlbl9lbmRwb2ludF9hdXRoX21ldGhvZCI6InVybjppZXRmOnBhcmFtczpvYXV0aDpjbGllbnQtYXNzZXJ0aW9uLXR5cGU6and0LWJlYXJlciIsImdyYW50X3R5cGVzIjpbImltcGxpY2l0Il0sInJlc3BvbnNlX3R5cGVzIjpbInRva2VuIiwiaWRfdG9rZW4iLCJpZF90b2tlbiB0b2tlbiJdLCJjbGllbnRfbmFtZSI6Ikdyb3dlclN5bmMiLCJjbGllbnRfdXJpIjoiaHR0cHM6Ly9mcGFkLmlvLyIsImNvbnRhY3RzIjpbIlNhbSBOb2VsIDxzYW5vZWxAcHVyZHVlLmVkdT4iXSwic29mdHdhcmVfaWQiOiJlNjMyYTdhNS02MmZjLTRlNzUtYTkwYy02MTE5YWFjYzEwZmUiLCJyZWdpc3RyYXRpb25fcHJvdmlkZXIiOiJodHRwczovL2lkZW50aXR5Lm9hZGEtZGV2LmNvbSIsImlhdCI6MTUwNzgyODYxM30.U_hlHdkLnAf3bBfgoHvfK7bretfIZszGsa5EuYxNjVZT-0Gm6NLOGa1hL-p1VxyBDwv8TRa0TBnb1beUTXNkucIGDQBI9rvZYTY9hHiYHVUddx0MrSL6g4X0N7SDfw_6lY8IbHNAKaDBcbDG97YmvV79xwxojiX8aDS6ouyf8yI
`.trim()

const defaultNewConnectionURL = 'https://localhost';

export default {
  oadaDomain,
  devtoolsPort,
  websiteDomain,
  metadata,
  defaultNewConnectionURL
}
