//Production Values
const devtoolsPort = 8585;
const oadaDomain = process.env.REACT_APP_OADA_DOMAIN || 'https://api.pspperfection.trellisfw.io';
const websiteDomain = 'https://certificationanalytics.trellisfw.io';
const metadata = require('./prod_metadata.js');
/*`
eyJqa3UiOiJodHRwczovL2lkZW50aXR5Lm9hZGEtZGV2LmNvbS9jZXJ0cyIsImtpZCI6ImtqY1NjamMzMmR3SlhYTEpEczNyMTI0c2ExIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJyZWRpcmVjdF91cmlzIjpbImh0dHBzOi8vY2VydGlmaWNhdGlvbmFuYWx5dGljcy5mcGFkLmlvL29hdXRoMi9yZWRpcmVjdC5odG1sIl0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoidXJuOmlldGY6cGFyYW1zOm9hdXRoOmNsaWVudC1hc3NlcnRpb24tdHlwZTpqd3QtYmVhcmVyIiwiZ3JhbnRfdHlwZXMiOlsiaW1wbGljaXQiXSwicmVzcG9uc2VfdHlwZXMiOlsidG9rZW4iLCJpZF90b2tlbiIsImlkX3Rva2VuIHRva2VuIl0sImNsaWVudF9uYW1lIjoiQ2VydGlmaWNhdGlvbkFuYWx5dGljcyIsImNsaWVudF91cmkiOiJodHRwczovL2ZwYWQuaW8vIiwiY29udGFjdHMiOlsiU2FtIE5vZWwgPHNhbm9lbEBwdXJkdWUuZWR1PiJdLCJzb2Z0d2FyZV9pZCI6ImZhMWViY2U0LTdkYTAtNDAwNS04MzJlLTlkYmRjYzRmNzYzYiIsInJlZ2lzdHJhdGlvbl9wcm92aWRlciI6Imh0dHBzOi8vaWRlbnRpdHkub2FkYS1kZXYuY29tIiwiaWF0IjoxNTA3ODI4MTM1fQ.LEpsmh2iUP_r9uvd7vJ0Dk4BFgf3LpzpkmtBwHjt8AjfkvFGJvRaG2hyRXWdH-5ehkrBYyalWI4Kq34MgDGi4vfyNMNoVEL7gn_4LiGqZ6WZXgLDYxi-YhKgKxIZ8I64Hp0OaqBZP0PG6x_O0A8iVP2k2tKmMI94KNQQwidU8rM
`.trim()*/

const defaultNewConnectionURL = 'https://api.pspperfection.trellisfw.io';

export default {
  oadaDomain,
  devtoolsPort,
  websiteDomain,
  metadata,
  defaultNewConnectionURL
}
