//Production Values
const devtoolsPort = 8585;
const apiDomain = process.env.REACT_APP_API_DOMAIN || 'https://api.abcaudits.fpad.io';
const oadaDomain = 'https://api.growersync.fpad.io';
const websiteDomain = 'https://growersync.fpad.io';
const metadata = `
eyJqa3UiOiJodHRwczovL2lkZW50aXR5Lm9hZGEtZGV2LmNvbS9jZXJ0cyIsImtpZCI6ImtqY1NjamMzMmR3SlhYTEpEczNyMTI0c2ExIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJyZWRpcmVjdF91cmlzIjpbImh0dHBzOi8vZ3Jvd2Vyc3luYy5mcGFkLmlvL29hdXRoMi9yZWRpcmVjdC5odG1sIl0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoidXJuOmlldGY6cGFyYW1zOm9hdXRoOmNsaWVudC1hc3NlcnRpb24tdHlwZTpqd3QtYmVhcmVyIiwiZ3JhbnRfdHlwZXMiOlsiaW1wbGljaXQiXSwicmVzcG9uc2VfdHlwZXMiOlsidG9rZW4iLCJpZF90b2tlbiIsImlkX3Rva2VuIHRva2VuIl0sImNsaWVudF9uYW1lIjoiR3Jvd2VyU3luYyIsImNsaWVudF91cmkiOiJodHRwczovL2ZwYWQuaW8vIiwiY29udGFjdHMiOlsiU2FtIE5vZWwgPHNhbm9lbEBwdXJkdWUuZWR1PiJdLCJzb2Z0d2FyZV9pZCI6IjRmMDU5YjU4LTM1ZjgtNGNkZC05YmQxLTM0MDcwMDFmZjY2MSIsInJlZ2lzdHJhdGlvbl9wcm92aWRlciI6Imh0dHBzOi8vaWRlbnRpdHkub2FkYS1kZXYuY29tIiwiaWF0IjoxNTA3ODI3ODM5fQ.neNVOTHC6XOkXsRisGhUpI0z_jxgoHEAVi2kiurO67c17nTwWgENPUWUjemcoiZK6ygIGgX94-SJh_Z6NDdvN4s0aMQjgOAgvfSQf0fXE5Ky1XWlKzT99_IQ90OMO2J28yWJGSwwLfd0Rly3aamiu-Uq0qpsFZzRQkWtYNBI-ZM
`.trim()

const defaultNewConnectionURL = 'https://api.abcaudits.fpad.io';

export default {
	apiDomain,
  oadaDomain,
  devtoolsPort,
  websiteDomain,
  metadata,
  defaultNewConnectionURL
}
