//Production Values
const devtoolsPort = 8585;
const oadaDomain = process.env.REACT_APP_OADA_DOMAIN || 'https://api.distributingexcellence.trellisfw.io';
const websiteDomain = 'https://distributingexcellence.trellisfw.io';
const metadata = `
eyJqa3UiOiJodHRwczovL2lkZW50aXR5Lm9hZGEtZGV2LmNvbS9jZXJ0cyIsImtpZCI6ImtqY1NjamMzMmR3SlhYTEpEczNyMTI0c2ExIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJyZWRpcmVjdF91cmlzIjpbImh0dHBzOi8vZGlzdHJpYnV0aW5nZXhjZWxsZW5jZS5mcGFkLmlvL29hdXRoMi9yZWRpcmVjdC5odG1sIl0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoidXJuOmlldGY6cGFyYW1zOm9hdXRoOmNsaWVudC1hc3NlcnRpb24tdHlwZTpqd3QtYmVhcmVyIiwiZ3JhbnRfdHlwZXMiOlsiaW1wbGljaXQiXSwicmVzcG9uc2VfdHlwZXMiOlsidG9rZW4iLCJpZF90b2tlbiIsImlkX3Rva2VuIHRva2VuIl0sImNsaWVudF9uYW1lIjoiRGlzdHJpYnV0aW5nRXhjZWxsZW5jZSIsImNsaWVudF91cmkiOiJodHRwczovL2ZwYWQuaW8vIiwiY29udGFjdHMiOlsiU2FtIE5vZWwgPHNhbm9lbEBwdXJkdWUuZWR1PiJdLCJzb2Z0d2FyZV9pZCI6ImFhYjlhOThmLTM3M2QtNGYwOS1iOTA5LTMzMWU3ODM3MzljYSIsInJlZ2lzdHJhdGlvbl9wcm92aWRlciI6Imh0dHBzOi8vaWRlbnRpdHkub2FkYS1kZXYuY29tIiwiaWF0IjoxNTA4Mjk0Mjk4fQ.DBAibrbqco_IWaeippnMufntefQu_hSck91Chv0sqILqWyxo9Vcdh5h9xFOO6c9mbhaueYZBHp4gbO_3GMhHDCw9Lg3xW5C3oxVWAdCYhoWZBM6xgkYu89AoyM7vodENBwSwl3sduxPYoPFvbz2W90N3-oLOKrQZOFDfXUefiJs
`.trim()

const defaultNewConnectionURL = 'https://api.pspperfection.trellisfw.io';

export default {
  oadaDomain,
  devtoolsPort,
  websiteDomain,
  metadata,
  defaultNewConnectionURL
}
